-- STORED PROCEDURE TO DELETE A QUESTION
CREATE PROCEDURE [dbo].[DeleteQuestion]
    @QuestionId INT
AS
BEGIN
    -- DELETE THE QUESTION RECORD AND CASCADE RELATED ANSWERS
    DELETE FROM Questions
    WHERE id = @QuestionId;
END;
GO

