-- STORED PROCEDURE TO FETCH ALL QUESTIONS
CREATE PROCEDURE [dbo].[GetAllQuestions]
AS
BEGIN
    -- SELECT ALL QUESTIONS` FROM THE QUESTIONS` TABLE
    SELECT id, question, options, correct
    FROM Questions;
END;
GO
