-- STORED PROCEDURE TO DELETE A QUIZ
CREATE PROCEDURE [dbo].[DeleteQuiz]
    @QuizId INT
AS
BEGIN
    -- DELETE THE QUIZ RECORD AND CASCADE TO RELATED TABLES
    DELETE FROM Quizzes
    WHERE id = @QuizId;

	-- DELETE ALL QUESTIONS ASSOCIATED WITH THAT QUIZ
	DELETE FROM Questions
	WHERE quiz_id = @QuizId
END;
GO

