name: Server Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Confirm server build pipeline is alive
        run: echo "Server build successful"
